title: Big Data Biology Lab at Fudan University
email: luispedro@big-data-biology.org
description: "The Big Data Biology Lab at Fudan University"
url: "http://big-data-biology.org"
twitter_username: luispedrocoelho
github_username:  luispedro
minimal_mistakes_skin: default
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: pretty
encoding: utf-8

defaults:
    - scope:
        path: ""
      values:
        layout: single

exclude:
    - update.sh
    - upload.sh
    - fix-mtimes.py
    - mtime_hash.pkl
    - default.nix
    - gemsets.nix
    - Gemset
    - Gemset.lock
permalink: /blog/:year/:month/:day/:title
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

